[package]
name = "bee-test"
version = "0.1.0"
authors = ["Lukas Tassanyi <lukas.tassanyi@iota.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.8"
rand = "0.7"